-- MySQL Script generated by MySQL Workbench
-- Thu May 14 19:41:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema registro_Envios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registro_Envios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registro_Envios` DEFAULT CHARACTER SET utf8 ;
USE `registro_Envios` ;

-- -----------------------------------------------------
-- Table `registro_Envios`.`remitente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_Envios`.`remitente` (
  `dni` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(13) NOT NULL,
  `email` VARCHAR(100) NULL,
  `calle` VARCHAR(100) NOT NULL,
  `altura` VARCHAR(5) NULL,
  `piso` VARCHAR(3) NULL,
  `depto` VARCHAR(10) NULL,
  `cp` VARCHAR(4) NOT NULL,
  `barrio` VARCHAR(100) NOT NULL,
  `localidad` VARCHAR(100) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_Envios`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_Envios`.`empleado` (
  `legajo` INT NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `cuil` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha-nacimiento` DATE NOT NULL,
  `fecha-ingreso` DATETIME NOT NULL,
  `fecha-egreso` DATETIME NULL,
  `estado` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `entrada_identrada` INT NOT NULL,
  PRIMARY KEY (`legajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_Envios`.`destinatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_Envios`.`destinatario` (
  `dni` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(13) NOT NULL,
  `email` VARCHAR(100) NULL,
  `calle` VARCHAR(100) NOT NULL,
  `altura` VARCHAR(5) NOT NULL,
  `piso` VARCHAR(3) NULL,
  `depto` VARCHAR(10) NULL,
  `cp` VARCHAR(4) NOT NULL,
  `barrio` VARCHAR(100) NOT NULL,
  `localidad` VARCHAR(100) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  `referencia` VARCHAR(255) NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_Envios`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_Envios`.`entrada` (
  `identrada` INT NOT NULL,
  `fecha-hora` DATETIME NULL,
  `id-codigo-paquete` VARCHAR(45) NULL,
  `id-remitente` VARCHAR(45) NULL,
  `legajo` VARCHAR(45) NULL,
  `empleado_legajo` INT NOT NULL,
  `destinatario_dni` INT NOT NULL,
  PRIMARY KEY (`identrada`),
  INDEX `fk_entrada_empleado1_idx` (`empleado_legajo` ASC) VISIBLE,
  INDEX `fk_entrada_destinatario1_idx` (`destinatario_dni` ASC) VISIBLE,
  CONSTRAINT `fk_entrada_empleado1`
    FOREIGN KEY (`empleado_legajo`)
    REFERENCES `registro_Envios`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_destinatario1`
    FOREIGN KEY (`destinatario_dni`)
    REFERENCES `registro_Envios`.`destinatario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_Envios`.`paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_Envios`.`paquete` (
  `idpaquete` INT NOT NULL,
  `dni_remitente` INT NOT NULL,
  `tipo_paquete` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `codigo-paquete` VARCHAR(45) NOT NULL,
  `remitente_dni` INT NOT NULL,
  `entrada_identrada` INT NOT NULL,
  `destinatario_dni` INT NOT NULL,
  PRIMARY KEY (`idpaquete`),
  INDEX `fk_paquete_remitente_idx` (`remitente_dni` ASC) VISIBLE,
  INDEX `fk_paquete_entrada1_idx` (`entrada_identrada` ASC) VISIBLE,
  INDEX `fk_paquete_destinatario1_idx` (`destinatario_dni` ASC) VISIBLE,
  CONSTRAINT `fk_paquete_remitente`
    FOREIGN KEY (`remitente_dni`)
    REFERENCES `registro_Envios`.`remitente` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_entrada1`
    FOREIGN KEY (`entrada_identrada`)
    REFERENCES `registro_Envios`.`entrada` (`identrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_destinatario1`
    FOREIGN KEY (`destinatario_dni`)
    REFERENCES `registro_Envios`.`destinatario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registro_Envios`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro_Envios`.`entrega` (
  `identrega` INT NOT NULL,
  `idpaquete` VARCHAR(45) NOT NULL,
  `id_dni_destinatario` INT NOT NULL,
  `legajo` INT NOT NULL,
  `fecha-hora` DATETIME NOT NULL,
  `empleado_legajo` INT NOT NULL,
  `destinatario_dni` INT NOT NULL,
  PRIMARY KEY (`identrega`),
  INDEX `fk_entrega_empleado1_idx` (`empleado_legajo` ASC) VISIBLE,
  INDEX `fk_entrega_destinatario1_idx` (`destinatario_dni` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_empleado1`
    FOREIGN KEY (`empleado_legajo`)
    REFERENCES `registro_Envios`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_destinatario1`
    FOREIGN KEY (`destinatario_dni`)
    REFERENCES `registro_Envios`.`destinatario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
